"""Pricing Scenario data model with JSON serialization and schema validation.

Implements the PricingScenario model conforming to the JSON Schema defined in the
design document. Supports serialization preserving 4 decimal places for monetary
values and deserialization with strict schema validation.

Validates: Requirements 14.1, 14.2, 14.4
"""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_serializer, model_validator


class StatusLabel(str, Enum):
    """Status labels for pricing scenarios based on risk classification."""

    RECOMMENDED = "Recommended"
    REVIEW_REQUIRED = "Review Required"
    HUMAN_EXCEPTION_HANDLING = "Human Exception Handling"


class RiskLevel(str, Enum):
    """Risk level classification for pricing scenarios."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class PriceChange(BaseModel):
    """A single product price change within a pricing scenario."""

    product_id: str = Field(..., alias="productId", description="Product identifier")
    current_price: float = Field(
        ..., alias="currentPrice", description="Current product price"
    )
    new_price: float = Field(..., alias="newPrice", description="Proposed new price")
    change_percent: float = Field(
        ..., alias="changePercent", description="Price change as a percentage"
    )

    model_config = {"populate_by_name": True}

    @field_serializer("current_price", "new_price", "change_percent")
    def serialize_monetary(self, value: float) -> float:
        """Preserve 4 decimal places for monetary values."""
        return round(value, 4)


class GuardrailResult(BaseModel):
    """Result of a guardrail evaluation for a pricing scenario."""

    rule: str = Field(..., description="Guardrail rule name")
    passed: bool = Field(..., description="Whether the scenario passed this rule")
    reason: str | None = Field(
        default=None, description="Reason for failure if not passed"
    )


class PricingScenario(BaseModel):
    """A data-driven pricing recommendation generated by the Strategy Synthesis Agent.

    Ranked by business impact with a confidence score and status label.
    Conforms to the Pricing Scenario JSON Schema defined in the design document.
    """

    scenario_id: str = Field(
        ..., alias="scenarioId", description="Unique scenario identifier"
    )
    cycle_id: str = Field(..., alias="cycleId", description="Parent pricing cycle ID")
    rank: int = Field(..., ge=1, description="Ordinal rank (1 = best)")
    confidence_score: int = Field(
        ...,
        alias="confidenceScore",
        ge=0,
        le=100,
        description="Confidence score (0-100)",
    )
    status_label: StatusLabel = Field(
        ..., alias="statusLabel", description="Scenario status label"
    )
    risk_level: RiskLevel = Field(
        ..., alias="riskLevel", description="Risk classification"
    )
    price_changes: list[PriceChange] = Field(
        ..., alias="priceChanges", description="List of product price changes"
    )
    projected_revenue: float = Field(
        ..., alias="projectedRevenue", description="Projected revenue impact"
    )
    projected_margin: float = Field(
        ..., alias="projectedMargin", description="Projected margin"
    )
    projected_market_share: float | None = Field(
        default=None,
        alias="projectedMarketShare",
        description="Projected market share change",
    )
    composite_score: float = Field(
        ..., alias="compositeScore", description="Weighted business impact score"
    )
    competitive_factors: dict[str, Any] = Field(
        ...,
        alias="competitiveFactors",
        description="Data from Competitive Intelligence Agent",
    )
    demand_factors: dict[str, Any] = Field(
        ..., alias="demandFactors", description="Data from Demand Forecasting Agent"
    )
    market_factors: dict[str, Any] = Field(
        ..., alias="marketFactors", description="Data from Market Intelligence Agent"
    )
    guardrail_results: list[GuardrailResult] | None = Field(
        default=None,
        alias="guardrailResults",
        description="Guardrail evaluation results",
    )

    model_config = {"populate_by_name": True}

    @field_serializer(
        "projected_revenue", "projected_margin", "projected_market_share",
        "composite_score",
    )
    def serialize_monetary(self, value: float | None) -> float | None:
        """Preserve 4 decimal places for monetary/numeric values."""
        if value is None:
            return None
        return round(value, 4)

    @model_validator(mode="before")
    @classmethod
    def validate_required_fields(cls, data: Any) -> Any:
        """Validate that required fields are present in the input data."""
        if isinstance(data, dict):
            required_fields = [
                "scenarioId", "cycleId", "rank", "confidenceScore",
                "statusLabel", "riskLevel", "priceChanges", "projectedRevenue",
                "projectedMargin", "compositeScore", "competitiveFactors",
                "demandFactors", "marketFactors",
            ]
            # Check using both alias and Python field names
            python_names = [
                "scenario_id", "cycle_id", "rank", "confidence_score",
                "status_label", "risk_level", "price_changes", "projected_revenue",
                "projected_margin", "composite_score", "competitive_factors",
                "demand_factors", "market_factors",
            ]
            for alias, python_name in zip(required_fields, python_names):
                if alias not in data and python_name not in data:
                    raise ValueError(f"Missing required field: '{alias}'")
        return data

    def to_json(self) -> str:
        """Serialize to JSON string using camelCase field names.

        Preserves 4 decimal places for monetary values.
        """
        return self.model_dump_json(by_alias=True)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary using camelCase field names.

        Preserves 4 decimal places for monetary values.
        """
        return self.model_dump(by_alias=True)

    @classmethod
    def from_json(cls, json_str: str) -> "PricingScenario":
        """Deserialize from JSON string with schema validation.

        Raises ValidationError if required fields are missing or types are wrong.
        """
        return cls.model_validate_json(json_str)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PricingScenario":
        """Deserialize from dictionary with schema validation.

        Raises ValidationError if required fields are missing or types are wrong.
        """
        return cls.model_validate(data)


# JSON Schema definition matching the design document
PRICING_SCENARIO_JSON_SCHEMA: dict[str, Any] = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "scenarioId", "cycleId", "rank", "confidenceScore", "statusLabel",
        "riskLevel", "priceChanges", "projectedRevenue", "projectedMargin",
        "compositeScore", "competitiveFactors", "demandFactors", "marketFactors",
    ],
    "properties": {
        "scenarioId": {"type": "string"},
        "cycleId": {"type": "string"},
        "rank": {"type": "integer", "minimum": 1},
        "confidenceScore": {"type": "integer", "minimum": 0, "maximum": 100},
        "statusLabel": {
            "type": "string",
            "enum": ["Recommended", "Review Required", "Human Exception Handling"],
        },
        "riskLevel": {"type": "string", "enum": ["LOW", "MEDIUM", "HIGH"]},
        "priceChanges": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["productId", "currentPrice", "newPrice", "changePercent"],
                "properties": {
                    "productId": {"type": "string"},
                    "currentPrice": {"type": "number"},
                    "newPrice": {"type": "number"},
                    "changePercent": {"type": "number"},
                },
            },
        },
        "projectedRevenue": {"type": "number"},
        "projectedMargin": {"type": "number"},
        "projectedMarketShare": {"type": "number"},
        "compositeScore": {"type": "number"},
        "competitiveFactors": {"type": "object"},
        "demandFactors": {"type": "object"},
        "marketFactors": {"type": "object"},
        "guardrailResults": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["rule", "passed"],
                "properties": {
                    "rule": {"type": "string"},
                    "passed": {"type": "boolean"},
                    "reason": {"type": "string"},
                },
            },
        },
    },
}
